apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: minikube-project  # Link to the project created above
  source:
    repoURL: https://github.com/Navneettdna/Kubenetes-test.git  # Your repository URL
    targetRevision: HEAD
    path: .  # Directory path to the app manifest in the repo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
